const ANALYTICS_EVENT_NAMES = {  // Can add these later if needed
  SHOW_BOTTOM_BAR: 'SHOW_BOTTOM_BAR',
  EXTERNAL_BUTTON_CLICKED: 'EXTERNAL_BUTTON_CLICKED',
  INITIAL_SUGGESTED_QUESTION_CLICKED: 'INITIAL_SUGGESTED_QUESTION_CLICKED',
  CHAT_AREA_OPEN: 'CHAT_AREA_OPEN',
  CHAT_AREA_CLOSE: 'CHAT_AREA_CLOSE',
  USER_SENT_FIRST_MESSAGE: "USER_SENT_FIRST_MESSAGE",
  MESSAGE_SENT: "MESSAGE_SENT",
  CTA_BUTTON_CLICKED: 'CTA_BUTTON_CLICKED',
  LINK_CLICKED_INSIDE_MESSAGE: "LINK_CLICKED_INSIDE_MESSAGE",
  DEMO_FORM_SUBMITTED: 'DEMO_FORM_SUBMITTED',
  SUGGESTED_QUESTION_CLICKED: 'SUGGESTED_QUESTION_CLICKED',
  VIDEO_ARTIFACT_PLAY: 'VIDEO_ARTIFACT_PLAY',
  VIDEO_ARTIFACT_PAUSE: 'VIDEO_ARTIFACT_PAUSE',
  VIDEO_ARTIFACT_COMPLETE: 'VIDEO_ARTIFACT_COMPLETE',
};

export default ANALYTICS_EVENT_NAMES;
