export const AGENT_INPUT_SEND_BUTTON_TOOLTIP_TEXT = 'Cannot send a message while AI is responding';
export const SUGGESTED_QUESTIONS_INTERVAL_DURATION_IN_CYCLE_IN_MS = 3000;

export enum DISCOVERY_QUESTION_ANSWER_TYPE {
  SINGLE_SELECT = 'SINGLE_SELECT',
  MULTI_SELECT = 'MULTI_SELECT',
  TEXT = 'TEXT',
}
