import type { TableRequestPayload, EntityMetadataResponse, FilterConfig } from '../types';

/**
 * Extract default values from manual filters (e.g., toggle filters)
 */
export const extractManualFilterDefaults = (filters?: FilterConfig[]): Record<string, unknown> => {
  const defaults: Record<string, unknown> = {};
  (filters || []).forEach((filter) => {
    if (filter.defaultValue !== undefined) {
      defaults[filter.id] = filter.defaultValue;
    }
  });
  return defaults;
};

/**
 * Generate filter configuration from entity metadata
 */

export const generateFilterConfig = (
  entityMetadata: EntityMetadataResponse | undefined,
  manualFilters: FilterConfig[] = [],
): FilterConfig[] => {
  const autoGeneratedFilters: FilterConfig[] = entityMetadata?.columns
    ? entityMetadata.columns
        .filter((col) => col.is_filterable)
        .map((col) => {
          // Hardcode optionsType and displayType based on cell_type since backend doesn't provide them
          let optionsType = (col.filter_options_type || 'DIRECT') as FilterConfig['optionsType'];
          let displayType = (col.filter_display_type || 'default') as FilterConfig['displayType'];

          // SDR Assignment: Show avatars and company logos
          if (col.column_name === 'sdr_assignment') {
            optionsType = 'ID_LOOKUP';
            displayType = 'user_avatar';
          }

          // Location: Show country flags
          if (col.cell_type === 'LOCATION_WITH_FLAG') {
            displayType = 'country_flag';
          }

          // Use data_lookup as filter key (extract primary lookup if it has fallbacks with ':')
          // Example: "email:details.website_url" -> use "email"
          // Replace dots with double underscores for nested lookups (e.g., "company.name" -> "company__name")
          const filterKey = col.data_lookup
            ? col.data_lookup.split(':')[0].trim().replace(/\./g, '__')
            : col.column_name;

          const config = {
            id: filterKey,
            label: col.filter_label!,
            type: (col.cell_type === 'DATETIME' ? 'date-range' : 'multi-select') as FilterConfig['type'],
            icon: col.filter_label_icon || undefined,
            displayType,
            optionsType,
            placeholder: `Select ${col.filter_label}`,
          };

          return config;
        })
    : [];

  // Merge manual filters from config (e.g., toggle filters) with auto-generated ones
  return [...manualFilters, ...autoGeneratedFilters];
};

/**
 * Build toggle filters map for controlling default filters
 * Returns a Map with the controlled filter field as key and an object with isEnabled and shouldInvert flags
 */
export const buildToggleFiltersMap = (
  filterConfig: FilterConfig[],
  urlStateFilters: Record<string, unknown>,
): Map<string, { isEnabled: boolean; shouldInvert: boolean }> => {
  const toggleFiltersMap = new Map<string, { isEnabled: boolean; shouldInvert: boolean }>();
  filterConfig
    .filter((f) => f.type === 'toggle' && f.controlsDefaultFilter)
    .forEach((toggleFilter) => {
      // Use the toggle's value from URL state, or fall back to defaultValue from config
      const urlValue = urlStateFilters[toggleFilter.id];
      const defaultValue = toggleFilter.defaultValue !== undefined ? toggleFilter.defaultValue : true;

      // Determine isEnabled based on URL value or default
      let isEnabled: boolean;
      if (urlValue === undefined || urlValue === null || urlValue === '_null_') {
        // No value in URL or explicitly cleared, use default
        isEnabled = defaultValue !== false;
      } else {
        // Has an explicit value in URL (including false), use it
        isEnabled = urlValue !== false && urlValue !== 'false';
      }

      const shouldInvert = toggleFilter.invertsDefaultFilterValue || false;
      toggleFiltersMap.set(toggleFilter.controlsDefaultFilter!, { isEnabled, shouldInvert });
    });
  return toggleFiltersMap;
};

/**
 * Add default filters to the filters array
 */
export const addDefaultFilters = (
  filtersArray: Array<{ field: string; value: unknown; operator?: string }>,
  allDefaultFilters: Record<string, unknown>,
  filterConfig: FilterConfig[],
  toggleFiltersMap: Map<string, { isEnabled: boolean; shouldInvert: boolean }>,
): void => {
  if (!allDefaultFilters) return;

  Object.entries(allDefaultFilters).forEach(([key, defaultValue]) => {
    // Skip toggle filters - they're not actual filters, just controllers
    const isToggleFilter = filterConfig.some((f) => f.id === key && f.type === 'toggle');
    if (isToggleFilter) {
      return;
    }

    // Check if this default filter is controlled by a toggle
    const toggleControl = toggleFiltersMap.get(key);
    const isControlledByToggle = !!toggleControl;

    if (isControlledByToggle) {
      // Two types of toggle-controlled filters:

      // Type 1: Normal toggle (e.g., "Company Revealed")
      // - Toggle ON → Add filter
      // - Toggle OFF → Skip filter
      if (!toggleControl.shouldInvert) {
        if (!toggleControl.isEnabled) {
          return; // Toggle is OFF, skip this default filter
        }
        // Toggle is ON, add the filter as-is
        if (defaultValue === null) {
          filtersArray.push({
            field: key,
            value: null,
            operator: 'is_not_null',
          });
        } else {
          filtersArray.push({
            field: key,
            value: defaultValue,
            operator: 'eq',
          });
        }
        return;
      }

      // Type 2: Inverted toggle (e.g., "Test Conversations" in Leads)
      // - Toggle OFF (default) → Add filter with original value (e.g., is_valid: true)
      // - Toggle ON → Add filter with inverted value (e.g., is_valid: false)
      // Always adds the filter, just inverts the value when toggle is ON
      let valueToUse = defaultValue;
      if (toggleControl.isEnabled && typeof defaultValue === 'boolean') {
        valueToUse = !defaultValue; // Invert the boolean value when toggle is ON
      }

      // Add the filter with potentially inverted value
      if (valueToUse === null) {
        filtersArray.push({
          field: key,
          value: null,
          operator: 'is_not_null',
        });
      } else {
        filtersArray.push({
          field: key,
          value: valueToUse,
          operator: 'eq',
        });
      }
    } else {
      // Non-toggle-controlled filters: skip if user has provided a different value
      // Example: "is_valid: true" - skip if user explicitly sets it to false
      if (key in allDefaultFilters && allDefaultFilters[key] !== defaultValue) {
        return;
      }

      if (defaultValue === null) {
        // Null values → is_not_null operator
        filtersArray.push({
          field: key,
          value: null,
          operator: 'is_not_null',
        });
      } else {
        // Non-null values (including false) → eq operator (e.g., is_test: false, is_valid: true, lead_type: 'GOAL_ACHIEVED')
        filtersArray.push({
          field: key,
          value: defaultValue,
          operator: 'eq',
        });
      }
    }
  });
};

/**
 * Add applied filters from URL state to the filters array
 */
export const addAppliedFilters = (
  filtersArray: Array<{ field: string; value: unknown; operator?: string }>,
  urlStateFilters: Record<string, unknown>,
  filterConfig: FilterConfig[],
  allDefaultFilters: Record<string, unknown>,
): void => {
  Object.entries(urlStateFilters).forEach(([key, value]) => {
    // Skip toggle filters - they only control other filters, not sent to API
    const isToggleFilter = filterConfig.some((f) => f.id === key && f.type === 'toggle');
    if (isToggleFilter) {
      return;
    }

    // Skip if this value equals the default filter value (already added above)
    const defaultValue = allDefaultFilters[key];
    if (value === defaultValue) {
      return;
    }

    // Skip null values (they're already handled by default filters)
    if (value === null) {
      filtersArray.push({
        field: key,
        value: null,
        operator: 'is_not_null',
      });
      return;
    }

    // Handle date range objects (from/to)
    if (typeof value === 'object' && value !== null && 'from' in value && 'to' in value) {
      const dateRange = value as { from: string | null; to: string | null };

      // Convert date strings to ISO timestamps with proper time values
      // Start date: 00:00:00.000, End date: 23:59:59.999
      const fromDate = dateRange.from ? new Date(dateRange.from) : null;
      const toDate = dateRange.to ? new Date(dateRange.to) : null;

      if (fromDate && toDate) {
        // Set start time to 00:00:00.000
        fromDate.setHours(0, 0, 0, 0);
        // Set end time to 23:59:59.999
        toDate.setHours(23, 59, 59, 999);

        filtersArray.push({
          field: key,
          value: [fromDate.toISOString(), toDate.toISOString()],
          operator: 'between',
        });
      }
      return;
    }

    // Add the applied filter
    if (Array.isArray(value) && value.length > 0) {
      filtersArray.push({
        field: key,
        value,
        operator: 'in',
      });
    } else if (value !== '' && value != null) {
      // Wrap single values in array and use 'in' operator (like V1)
      filtersArray.push({
        field: key,
        value: [value],
        operator: 'in',
      });
    }
  });
};

/**
 * Build the complete request payload for the table API
 */
export const buildRequestPayload = (
  urlState: {
    filters: Record<string, unknown>;
    sortBy?: string | null;
    sortOrder?: 'asc' | 'desc' | null;
    page: number;
    pageSize: number;
    search?: string;
  },
  allDefaultFilters: Record<string, unknown>,
  filterConfig: FilterConfig[],
): TableRequestPayload => {
  const filtersArray: Array<{ field: string; value: unknown; operator?: string }> = [];

  // Build toggle filters map
  const toggleFiltersMap = buildToggleFiltersMap(filterConfig, urlState.filters);

  // Add default filters
  addDefaultFilters(filtersArray, allDefaultFilters, filterConfig, toggleFiltersMap);

  // Add applied filters
  addAppliedFilters(filtersArray, urlState.filters, filterConfig, allDefaultFilters);

  const payload = {
    filters: filtersArray,
    sort: urlState.sortBy && urlState.sortOrder ? [{ field: urlState.sortBy, order: urlState.sortOrder }] : [],
    page: urlState.page,
    page_size: urlState.pageSize,
    search: urlState.search || '',
  };

  return payload;
};

/**
 * Calculate the number of applied filters (excluding default filters)
 */
export const calculateAppliedFiltersCount = (
  urlStateFilters: Record<string, unknown>,
  urlStateSearch?: string,
  allDefaultFilters?: Record<string, unknown>,
): number => {
  let count = 0;
  const defaultFilterKeys = new Set(Object.keys(allDefaultFilters || {}));

  Object.entries(urlStateFilters).forEach(([key, value]) => {
    // Skip default filters
    if (defaultFilterKeys.has(key)) {
      return;
    }

    if (value === null || value === undefined || value === '') {
      return;
    }
    if (Array.isArray(value) && value.length === 0) {
      return;
    }
    count++;
  });

  if (urlStateSearch) {
    count++;
  }

  return count;
};

/**
 * Helper to get row by ID from table data
 */
export const getRowById = <TRow>(
  tableData: { results: TRow[] } | undefined,
  rowKeyColumn: string,
  id: string,
): TRow | undefined => {
  if (!tableData?.results) return undefined;
  // Convert both to string for comparison (URL params are always strings)
  return tableData.results.find((row) => String((row as Record<string, unknown>)[rowKeyColumn]) === id);
};
