export enum MessageViewType {
  ADMIN_MESSAGE_IN_ADMIN_VIEW = 'ADMIN_MESSAGE_IN_ADMIN_VIEW',
  ADMIN_MESSAGE_IN_USER_VIEW = 'ADMIN_MESSAGE_IN_USER_VIEW',
  ADMIN_MESSAGE_IN_DASHBOARD_VIEW = 'ADMIN_MESSAGE_IN_DASHBOARD_VIEW',
  USER_MESSAGE_IN_ADMIN_VIEW = 'USER_MESSAGE_IN_ADMIN_VIEW',
  USER_MESSAGE_IN_USER_VIEW = 'USER_MESSAGE_IN_USER_VIEW',
  USER_MESSAGE_IN_DASHBOARD_VIEW = 'USER_MESSAGE_IN_DASHBOARD_VIEW',
  AI_MESSAGE_IN_ADMIN_VIEW = 'AI_MESSAGE_IN_ADMIN_VIEW',
  AI_MESSAGE_IN_USER_VIEW = 'AI_MESSAGE_IN_USER_VIEW',
  AI_MESSAGE_IN_DASHBOARD_VIEW = 'AI_MESSAGE_IN_DASHBOARD_VIEW',
}

export enum ViewType {
  USER = 'USER',
  DASHBOARD = 'DASHBOARD',
  ADMIN = 'ADMIN',
}

export enum MessageSenderRole {
  AI = 'ai',
  ADMIN = 'admin',
  USER = 'user',
  SYSTEM = 'system',
}

export enum ArtifactEnum {
  SLIDE = 'SLIDE',
  VIDEO = 'VIDEO',
  SLIDE_IMAGE = 'SLIDE_IMAGE',
  NONE = 'NONE',
  SUGGESTIONS = 'SUGGESTIONS',
  FORM = 'FORM',
  CALENDAR = 'CALENDAR',
  DEMO = 'DEMO',
}

export enum ArtifactPreviewEnum {
  SLIDE = 'SLIDE',
  SLIDE_IMAGE = 'SLIDE_IMAGE',
  VIDEO = 'VIDEO',
  DEMO = 'DEMO',
}

export enum CalendarTypeEnum {
  CALENDLY = 'CALENDLY',
  CAL_COM = 'CAL_COM',
  IFRAME = 'IFRAME',
  HUBSPOT = 'HUBSPOT',
  BREAKOUT = 'BREAKOUT',
}
